application: hollrin1
version: 1
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /media
  static_dir: _generated_media

- url: /callme/cron1/
  script: cron1.py

- url: /callme/cron/
  script: cron.py

- url: /.*
  script: common/appenginepatch/main.py
